apiVersion: apps/v1
kind: Deployment
metadata:
  name: beginner-py-bot
  labels:
    app: beginner-py-bot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: beginner-py-bot
  template:
    metadata:
      labels:
        app: beginner-py-bot
    spec:
      containers:
      - name: beginner-py-bot
        image: zzmmrmn/beginner-py-bot:2019.11.12
        env:
          - name: "DISCORD_TOKEN"
            valueFrom:
              secretKeyRef:
                name: discord.token
                key: token
