apiVersion: apps/v1
kind: Deployment
metadata:
  name: beginner-py-bot-dev
  labels:
    app: beginner-py-bot-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: beginner-py-bot-dev
  template:
    metadata:
      labels:
        app: beginner-py-bot-dev
    spec:
      containers:
        - name: beginner-py-bot
          image: zzmmrmn/beginner-py-bot-dev:<IMAGE_VERSION>
          env:
            - name: BPY_MONTHLY_SHOWING_OFF_CHANNEL_ID
              value: "863925515768037406"
            - name: PRODUCTION_BOT
              value: "PRODUCTION"
            - name: "DISCORD_TOKEN"
              valueFrom:
                secretKeyRef:
                  name: discord.dev.token
                  key: token
            - name: "BOT_IMAGE_VERSION"
              value: "<IMAGE_VERSION>"
            - name: "DB_HOST"
              value: "private-personal-postgres-cluster-1-apr-26-backup-do-user-87772.a.db.ondigitalocean.com"
            - name: "DB_PORT"
              value: "25061"
            - name: "DB_USER"
              value: "beginnerpy"
            - name: "DB_NAME"
              value: "bpydb-pool"
            - name: "DB_PASSWORD"
              valueFrom:
                secretKeyRef:
                  name: postgres-password
                  key: password
