apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: beginner-py-bot-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: beginner-py-bot
  labels:
    app: beginner-py-bot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: beginner-py-bot
  template:
    metadata:
      labels:
        app: beginner-py-bot
    spec:
      containers:
        - name: beginner-py-bot
          image: zzmmrmn/beginner-py-bot:0.0.19
          volumeMounts:
            - name: beginner-py-bot-vol
              mountPath: /usr/src/app/data
          env:
            - name: PRODUCTION_BOT
              value: "PRODUCTION"
            - name: "DISCORD_TOKEN"
              valueFrom:
                secretKeyRef:
                  name: discord.token
                  key: token
            - name: "DB_HOST"
              value: "bpy-postgres-svc"
            - name: "DB_PASSWORD"
              valueFrom:
                secretKeyRef:
                  name: postgres-password
                  key: password
      volumes:
        - name: beginner-py-bot-vol
          persistentVolumeClaim:
            claimName: beginner-py-bot-pvc
