version: "3.2"
services:
  postgres_db:
    image: "postgres:12.1"
    container_name: "my_postgres"
    environment:
      - POSTGRES_USER=postgresadmin
      - POSTGRES_PASSWORD=dev-env-password-safe-to-be-public
      - POSTGRES_DB=bpydb
    expose:
      - "5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  site:
    build: ../site
    depends_on:
      - postgres_db
    ports:
      - target: 8080
        published: 8080
        protocol: tcp
    env_file:
      - ../site/site.config
